version: '2'
services:

  devpi:
      image: hongtianjun/devpiserver
    volumes:
      - ./data:/data
    ports:
      - 3141:3141
    environment:
      - DEVPI_PASSWORD=123456
    restart: always
